### ISSUE TITLE
Ошибка после при загрузке песен

### ISSUE THREAD

**Issue by Marty25** [Scorpio92/vkmd2#4]
Здравствуйте. После ввода логина и пароля приложение никак не может загрузить песни. 
![photo_2018-07-03_07-35-04](https://user-images.githubusercontent.com/19392655/42197410-b8d510ec-7e93-11e8-93d6-add0ed616d79.jpg)

На эмуляторе такой проблемы нет. Собирал сам со своим google-services.json.
Вижу ошибку при запуске. Не из-за нее ли?

E/LOGGER: OOPS...EXCEPTION!
          java.lang.IllegalArgumentException: currentTrack is null
              at ru.scorpio92.vkmd2.service.AudioService.sendBroadcastToActivity(AudioService.java:403)
              at ru.scorpio92.vkmd2.service.AudioService.handleAction(AudioService.java:223)
              at ru.scorpio92.vkmd2.service.AudioService.onStartCommand(AudioService.java:161)
              at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3539)
              at android.app.ActivityThread.-wrap20(Unknown Source:0)
              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
              at android.os.Handler.dispatchMessage(Handler.java:105)
              at android.os.Looper.loop(Looper.java:164)
              at android.app.ActivityThread.main(ActivityThread.java:6541)
              at java.lang.reflect.Method.invoke(Native Method)
              at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by Scorpio92** [comment]
Здравствуйте! Скачайте последние исходники или сделайте git pull (если вы клонировали репозиторий). Такой проблемы сейчас быть не должно.

**Comment by Marty25** [comment]
Актуально. Песни загружаются после перезахода в приложение.

**Comment by Scorpio92** [comment]
Не совсем понял. Работает после сборки из последних исходников?
Приложение точно должно работать с коммита: https://github.com/Scorpio92/vkmd2/commit/e16bc3fcf71ba41c25b5ff898018d15fa141e285

**Comment by Marty25** [comment]
Да, с последних исходников оно работает. На эмуляторе без проблем. На 2 смартфонах проверял - та же проблема, что на скрине выше. Т.е. песни появляются после перезахода.

**Comment by Scorpio92** [comment]
А на каких устройствах возникает проблема (версия ОС, название устр-ва)? Опишите подробно последовательность действий.
Самостоятельно можно попробовать продебажить метод  https://github.com/Scorpio92/vkmd2/blob/master/app/src/main/java/ru/scorpio92/vkmd2/tools/VkmdUtils.java. Проверить, возвращает ли он массив треков.

**Comment by Scorpio92** [comment]
Метод: getTrackListFromPageCode
